Migrate from Anko to Room
readium/r2-lcp-kotlin pull request #116
Opened 2021-08-14 20:41 UTC by stevenzeck

2021-08-14 20:57 UTC, stevenzeck commented
Leaving in draft until I figure out why the dialog for inputting the passphrase isn't showing much.

2021-08-15 10:57 UTC, mickael-menu commented
Nice, thanks!

I created a dedicated 3.0.0 epic to list the changes to be made: https://github.com/readium/r2-testapp-kotlin/issues/454

2021-08-17 01:02 UTC, stevenzeck commented
Do you want to be rid of needing a database for this by 3.0? If not, then this is fine, but we should deprecate the relevant functions/vals sooner than later.

2021-08-17 07:22 UTC, mickael-menu commented
> Do you want to be rid of needing a database for this by 3.0? If not, then this is fine, but we should deprecate the relevant functions/vals sooner than later.

Not necessarily as it's convenient to have a default implementation. The idea is to give the control back to the apps if they want it though, regarding passphrase persistence.

2021-08-18 02:16 UTC, stevenzeck commented
I also changed how the Bluetooth adapter's name is retrieved, as `BluetoothAdapter.getDefaultAdapter()` is deprecated with API 31.

There is plenty of other refactoring that can be done, especially with the checks to `exists` and `isDeviceRegistered`, but another day.

2021-09-07 08:11 UTC, mickael-menu requested changes

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/persistence/Licenses.kt
> +data class Licenses(
```suggestion
internal data class License(
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/persistence/Licenses.kt
> +    val registered: Boolean? = false,
```suggestion
    val registered: Boolean = false,
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/persistence/Licenses.kt
> +    var id: String?,
```suggestion
    var licenseId: String,
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/persistence/Transactions.kt
> +data class Transactions(
```suggestion
internal data class Passphrase(
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/persistence/Transactions.kt
> +    val passphrase: String?,
```suggestion
    val passphrase: String,
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/service/DeviceRepository.kt
> +class DeviceRepository(private val lcpDao: LcpDao) {
We should keep the repositories private.

```suggestion
internal class DeviceRepository(private val lcpDao: LcpDao) {
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/persistence/Database.kt
> +abstract class LcpDatabase : RoomDatabase() {
```suggestion
internal abstract class LcpDatabase : RoomDatabase() {
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/service/LicensesRepository.kt
> +        val license = Licenses(licenseDocument.id, licenseDocument.rights.print, licenseDocument.rights.copy)
Since the arguments are a bunch of simple types, using named parameters is safer in case the order changes or is messed up.

```suggestion
        val license = License(licenseId = licenseDocument.id, rightPrint = licenseDocument.rights.print, rightCopy = licenseDocument.rights.copy)
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/service/PassphrasesRepository.kt
> +class PassphrasesRepository(private val lcpDao: LcpDao) {
```suggestion
internal class PassphrasesRepository(private val lcpDao: LcpDao) {
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/service/PassphrasesRepository.kt
> +        val transaction = Transactions(licenseId, provider, userId, passphraseHash)
Same for named parameters.

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/service/LicensesRepository.kt
> +class LicensesRepository(private val lcpDao: LcpDao) {
```suggestion
internal class LicensesRepository(private val lcpDao: LcpDao) {
```

2021-09-07 08:11 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/service/PassphrasesService.kt
> +            }
I think it's fine if the user id is `null`, we still want to add the passphrase to the DB. Any particular reason for changing this?

2021-09-09 09:39 UTC, mickael-menu approved these changes
Great improvement, thank you!

2021-09-09 09:54 UTC, merged