Some changes in LcpService API
readium/r2-lcp-kotlin pull request #89
Opened 2020-08-26 15:27 UTC by qnga

Libraries are likely to use only [Automatic Key Retrieval](https://readium.org/lcp-specs/notes/lcp-key-retrieval.html#automatic-lcp-key-retrieval-use-of-authentication-for-opds) without any UI to input the passphrase.

Therefore, I think `LcpAuthenticating` may be optional in `LcpService.contentProtection` and `LcpService` should expose a simple way to add a passphrase to the repository.

2020-08-31 07:01 UTC, mickael-menu requested changes
### Making `LcpAuthenticating` optional

An app must always be able to present a prompt for the passphrase, because:

* The LCP key retrieval might fail for some reason.
* It's required by the certification.

So I think we should keep the `LcpAuthenticating` required.


### Adding a passphrase

Thanks, that's a useful addition. I'd like to make some changes to the API, because:

* We might not always have access to the license information with the passphrase, so it should be optional.
* From [User Key Processing](https://readium.org/lcp-specs/releases/lcp/latest.html#73-user-key-processing):
  > Reading Systems may associate specific User Keys with specific Providers and User IDs in order to optimize the discovery of the correct User Key to process a License Document.
* It might be useful to add either a clear, or already hashed passphrase.

So we could have:

```kotlin
suspend fun addPassphrase(passphrase: String, hashed: Boolean, license: LicenseDocument) =
    addPassphrase(passphrase, hashed, provider = license.provider, userId = license.user.id

suspend fun addPassphrase(passphrase: String, hashed: Boolean, licenseId: String? = null, provider: String? = null, userId: String? = null) {
    ...
}
```

2020-09-17 08:26 UTC, mickael-menu commented on r2-lcp/src/main/java/org/readium/r2/lcp/service/PassphrasesService.kt
> +        passphrases.addAll(repository.allPassphrases())
@qnga A `linkedSetOf<String>()` could make sense for `passphrases`, to avoid testing duplicates introduced by `repository.allPassphrases`.

2020-09-17 08:40 UTC, qnga commented on r2-lcp/src/main/java/org/readium/r2/lcp/service/PassphrasesService.kt
> +        passphrases.addAll(repository.allPassphrases())
I don't know the cost of testing a passphrase, but it seems to be a good idea.

2020-09-17 12:48 UTC, mickael-menu approved these changes

2020-09-17 12:48 UTC, merged